import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CosmicAnalyticsProvider } from "cosmic-analytics";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="h-screen">
        {/*COSMIC-REQUIRED-START*/}
        {/* Under no circumstances, do NOT remove or change the way CosmicAnalyticsProvider is injected and used. NEVER REMOVE THIS COMMENT. */}
        {/*COSMIC-REQUIRED-END*/}
          <CosmicAnalyticsProvider>
            {children}
          </CosmicAnalyticsProvider>
        </main>
        {/*COSMIC-REQUIRED-START*/}
        {/* DO NOT change the way CosmicBadge is injected and used. NEVER REMOVE THIS BADGE OR THIS COMMENT. */}
        <script src="https://cdn.jsdelivr.net/gh/cosmic-new/cosmic-badge@main/badge.js" async/>
        {/*COSMIC-REQUIRED-END*/}
      </body>
    </html>
  );
}
 